// 项目数据
// 按照实际images/projects目录的图片文件组织，使用真实项目名称

export const projects = [
  {
    id: 'one-park-gubei',
    name: '古北壹号',
    location: '上海 · 中国',
    client: '万科集团',
    year: '2023',
    grossFloorArea: '120,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    subCategory: 'landscape',
    landscapeImages: [
      '/images/projects/one-park-gubei/28-one-park-gubei',
      '/images/projects/one-park-gubei/22-one-park-gubei',
      '/images/projects/one-park-gubei/23-one-park-gubei',
      '/images/projects/one-park-gubei/24-one-park-gubei',
      '/images/projects/one-park-gubei/25-one-park-gubei',
      '/images/projects/one-park-gubei/26-one-park-gubei',
      '/images/projects/one-park-gubei/27-one-park-gubei',
    ],
    imagePath: '/images/projects/01-one-park-gubei',
    gallery: [
      '/images/projects/one-park-gubei/01-one-park-gubei',
      '/images/projects/one-park-gubei/02-one-park-gubei',
      '/images/projects/one-park-gubei/03-one-park-gubei',
      '/images/projects/one-park-gubei/04-one-park-gubei',
      '/images/projects/one-park-gubei/05-one-park-gubei',
      '/images/projects/one-park-gubei/06-one-park-gubei',
      '/images/projects/one-park-gubei/07-one-park-gubei',
      '/images/projects/one-park-gubei/08-one-park-gubei',
      '/images/projects/one-park-gubei/09-one-park-gubei',
      '/images/projects/one-park-gubei/10-one-park-gubei',
      '/images/projects/one-park-gubei/11-one-park-gubei',
      '/images/projects/one-park-gubei/12-one-park-gubei',
      '/images/projects/one-park-gubei/13-one-park-gubei',
      '/images/projects/one-park-gubei/14-one-park-gubei',
      '/images/projects/one-park-gubei/15-one-park-gubei',
      '/images/projects/one-park-gubei/16-one-park-gubei',
      '/images/projects/one-park-gubei/17-one-park-gubei',
      '/images/projects/one-park-gubei/18-one-park-gubei',
      '/images/projects/one-park-gubei/19-one-park-gubei',
      '/images/projects/one-park-gubei/20-one-park-gubei',
      '/images/projects/one-park-gubei/21-one-park-gubei',
      '/images/projects/one-park-gubei/22-one-park-gubei',
      '/images/projects/one-park-gubei/23-one-park-gubei',
      '/images/projects/one-park-gubei/24-one-park-gubei',
      '/images/projects/one-park-gubei/25-one-park-gubei',
      '/images/projects/one-park-gubei/26-one-park-gubei',
      '/images/projects/one-park-gubei/27-one-park-gubei',
      '/images/projects/one-park-gubei/28-one-park-gubei',
    ],
    description: '古北地区的城市更新项目，融合传统与现代，打造宜居社区。设计理念源于对上海里弄文化的现代诠释，通过创新的空间组织方式，实现高密度环境下的居住品质提升。',
  },
  {
    id: 'royal-pavilion',
    name: '华山公寓',
    location: '上海 · 中国',
    client: '华润置地',
    year: '2022',
    grossFloorArea: '45,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    imagePath: '/images/projects/02-RoyalPavilion',
    gallery: [
      '/images/projects/royal-pavilion/01-royal-pavilion',
      '/images/projects/royal-pavilion/02-royal-pavilion',
      '/images/projects/royal-pavilion/03-royal-pavilion',
      '/images/projects/royal-pavilion/04-royal-pavilion',
      '/images/projects/royal-pavilion/05-royal-pavilion',
      '/images/projects/royal-pavilion/06-royal-pavilion',
      '/images/projects/royal-pavilion/07-royal-pavilion',
      '/images/projects/royal-pavilion/08-royal-pavilion',
      '/images/projects/royal-pavilion/09-royal-pavilion',
      '/images/projects/royal-pavilion/10-royal-pavilion',
      '/images/projects/royal-pavilion/11-royal-pavilion',
      '/images/projects/royal-pavilion/12-royal-pavilion',
      '/images/projects/royal-pavilion/13-royal-pavilion',
      '/images/projects/royal-pavilion/14-royal-pavilion',
      '/images/projects/royal-pavilion/15-royal-pavilion',
      '/images/projects/royal-pavilion/16-royal-pavilion',
      '/images/projects/royal-pavilion/17-royal-pavilion',
    ],
    description: '位于上海市核心区的高端住宅公寓项目，融合现代城市生活与自然景观视野。设计强调空间功能性与居住品质，采用开放式布局和精选材料营造舒适居住体验。',
  },
  {
    id: 'upper-east',
    name: '尚东鼎',
    location: '上海 · 中国',
    client: '私人业主',
    year: '2022',
    grossFloorArea: '85,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    subCategory: 'landscape',
    landscapeImages: [
      '/images/projects/upper-east/06-upper-east',
      '/images/projects/upper-east/02-upper-east',
      '/images/projects/upper-east/04-upper-east',
    ],
    imagePath: '/images/projects/03-upper-east',
    gallery: [
      '/images/projects/upper-east/01-upper-east',
      '/images/projects/upper-east/02-upper-east',
      '/images/projects/upper-east/03-upper-east',
      '/images/projects/upper-east/04-upper-east',
      '/images/projects/upper-east/05-upper-east',
      '/images/projects/upper-east/06-upper-east',
      '/images/projects/upper-east/07-upper-east',
      '/images/projects/upper-east/08-upper-east',
      '/images/projects/upper-east/09-upper-east',
      '/images/projects/upper-east/10-upper-east',
    ],
    description: '上海浦东高端住宅项目，融合现代城市生活与自然景观视野。设计强调空间功能性与居住品质，采用开放式布局和精选材料营造舒适居住体验。',
  },
  {
    id: 'rongxinarc',
    name: '杭州融信',
    location: '杭州 · 中国',
    client: '融创中国',
    year: '2020',
    grossFloorArea: '180,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    imagePath: '/images/projects/04-rongxinarc',
    gallery: [
      '/images/projects/rongxinarc/01-rongxinarc',
      '/images/projects/rongxinarc/02-rongxinarc',
      '/images/projects/rongxinarc/03-rongxinarc',
      '/images/projects/rongxinarc/04-rongxinarc',
      '/images/projects/rongxinarc/05-rongxinarc',
      '/images/projects/rongxinarc/06-rongxinarc',
      '/images/projects/rongxinarc/07-rongxinarc',
      '/images/projects/rongxinarc/08-rongxinarc',
    ],
    description: '创新型科技园区，以"产城融合"为设计理念，打造工作、生活、学习一体化的创新生态系统。建筑群体采用模块化设计策略，适应未来发展需求。',
  },
  {
    id: 'macalline-anji',
    name: '安吉度假别墅',
    location: '安吉 · 中国',
    client: '红星美凯龙',
    year: '2021',
    grossFloorArea: '12,000 m²',
    status: 'proposed',
    statusLabel: '提案中',
    category: 'architecture',
    categoryLabel: '建筑',
    imagePath: '/images/projects/05-macalline-anji',
    gallery: [
      '/images/projects/macalline-anji/01-macalline-anji',
      '/images/projects/macalline-anji/02-macalline-anji',
      '/images/projects/macalline-anji/03-macalline-anji',
    ],
    description: '安吉竹林中的度假别墅设计，以"隐逸山林"为设计理念，创造与自然共生的居住体验。建筑采用乡土材料和被动式设计策略，实现环境可持续性。',
  },
  {
    id: 'prime-dynapolis',
    name: '品尊国际（三期）',
    location: '上海 · 中国',
    client: '万科集团',
    year: '2023',
    grossFloorArea: '85,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    subCategory: 'landscape',
    imagePath: '/images/projects/06-prime-dynapolis',
    gallery: [
      '/images/projects/prime-dynapolis/01-prime-dynapolis',
      '/images/projects/prime-dynapolis/02-prime-dynapolis',
      '/images/projects/prime-dynapolis/03-prime-dynapolis',
      '/images/projects/prime-dynapolis/04-prime-dynapolis',
      '/images/projects/prime-dynapolis/05-prime-dynapolis',
      '/images/projects/prime-dynapolis/06-prime-dynapolis',
      '/images/projects/prime-dynapolis/07-prime-dynapolis',
      '/images/projects/prime-dynapolis/08-prime-dynapolis',
      '/images/projects/prime-dynapolis/09-prime-dynapolis',
      '/images/projects/prime-dynapolis/10-prime-dynapolis',
      '/images/projects/prime-dynapolis/11-prime-dynapolis',
      '/images/projects/prime-dynapolis/12-prime-dynapolis',
    ],
    landscapeImages: [
      '/images/projects/prime-dynapolis/13-prime-dynapolis',
      '/images/projects/prime-dynapolis/14-prime-dynapolis',
      '/images/projects/prime-dynapolis/15-prime-dynapolis',
      '/images/projects/prime-dynapolis/16-prime-dynapolis',
      '/images/projects/prime-dynapolis/17-prime-dynapolis',
      '/images/projects/prime-dynapolis/18-prime-dynapolis',
    ],
    interiorImages: [
      '/images/projects/prime-dynapolis/19-prime-dynapolis',
    ],
    description: '品尊国际项目的第三期开发，延续前期的城市更新理念，进一步融合现代居住功能与历史建筑肌理。设计强调空间创新与社区活力。',
  },
  {
    id: 'moment-to-cloud',
    name: '开云·艾尚里',
    location: '开化 · 中国',
    client: '开化市政府',
    year: '2022',
    grossFloorArea: '55,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'architecture',
    categoryLabel: '建筑',
    subCategory: 'landscape',
    imagePath: '/images/projects/07-moment-to-cloud',
    gallery: [
      '/images/projects/moment-to-cloud/01-moment-to-cloud',
      '/images/projects/moment-to-cloud/02-moment-to-cloud',
      '/images/projects/moment-to-cloud/03-moment-to-cloud',
      '/images/projects/moment-to-cloud/04-moment-to-cloud',
      '/images/projects/moment-to-cloud/05-moment-to-cloud',
      '/images/projects/moment-to-cloud/06-moment-to-cloud',
      '/images/projects/moment-to-cloud/07-moment-to-cloud',
      '/images/projects/moment-to-cloud/08-moment-to-cloud',
      '/images/projects/moment-to-cloud/09-moment-to-cloud',
      '/images/projects/moment-to-cloud/10-moment-to-cloud',
    ],
    landscapeImages: [
      '/images/projects/moment-to-cloud/11-moment-to-cloud',
      '/images/projects/moment-to-cloud/12-moment-to-cloud',
      '/images/projects/moment-to-cloud/13-moment-to-cloud',
      '/images/projects/moment-to-cloud/14-moment-to-cloud',
      '/images/projects/moment-to-cloud/15-moment-to-cloud',
    ],
    description: '开化老城区的城市更新项目，融合传统建筑文化与现代都市功能。设计理念源于对开化历史街区的当代诠释，创造适应现代生活需求的文化社区。',
  },
  {
    id: 'lot-hk231',
    name: '新湖·天虹',
    location: '嘉兴 · 中国',
    client: '新湖中宝',
    year: '2024',
    grossFloorArea: '78,000 m²',
    status: 'under-construction',
    statusLabel: '建设中',
    category: 'architecture',
    categoryLabel: '建筑',
    imagePath: '/images/projects/08-lot-hk231',
    gallery: [
      '/images/projects/lot-hk231/01-lot-hk231',
      '/images/projects/lot-hk231/02-lot-hk231',
      '/images/projects/lot-hk231/03-lot-hk231',
      '/images/projects/lot-hk231/04-lot-hk231',
    ],
    description: '嘉兴滨湖新区的高端住宅项目，以"虹桥之韵"为设计灵感，创造连接自然与都市的居住空间。设计强调水岸空间与建筑形态的有机融合。',
  },
  {
    id: 'chairclub',
    name: 'Chair Club',
    location: '上海 · 中国',
    client: '私人业主',
    year: '2021',
    grossFloorArea: '800 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'interior',
    categoryLabel: '室内',
    interiorImages: [
      '/images/projects/chairclub/01-chairclub',
      '/images/projects/chairclub/02-chairclub',
      '/images/projects/chairclub/03-chairclub',
      '/images/projects/chairclub/04-chairclub',
      '/images/projects/chairclub/05-chairclub',
    ],
    imagePath: '/images/projects/09-chairclub',
    gallery: [
      '/images/projects/chairclub/01-chairclub',
      '/images/projects/chairclub/02-chairclub',
      '/images/projects/chairclub/03-chairclub',
      '/images/projects/chairclub/04-chairclub',
      '/images/projects/chairclub/05-chairclub',
    ],
    description: '上海法租界内的历史建筑室内改造项目，以"Chair Club"为设计主题，创造融合当代艺术与历史氛围的会员制空间。设计强调材料对话与空间叙事。',
  },
  {
    id: 'content-office-shop',
    name: 'Content Office & Shop',
    location: '上海 · 中国',
    client: '万科集团',
    year: '2020',
    grossFloorArea: '2,800 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'interior',
    categoryLabel: '室内',
    interiorImages: [
      '/images/projects/content-office-shop/01-content-office-shop',
      '/images/projects/content-office-shop/02-content-office-shop',
      '/images/projects/content-office-shop/03-content-office-shop',
      '/images/projects/content-office-shop/04-content-office-shop',
      '/images/projects/content-office-shop/05-content-office-shop',
      '/images/projects/content-office-shop/06-content-office-shop',
      '/images/projects/content-office-shop/07-content-office-shop',
      '/images/projects/content-office-shop/10-content-office-shop',
    ],
    imagePath: '/images/projects/10-content-office-shop',
    gallery: [
      '/images/projects/content-office-shop/01-content-office-shop',
      '/images/projects/content-office-shop/02-content-office-shop',
      '/images/projects/content-office-shop/03-content-office-shop',
      '/images/projects/content-office-shop/04-content-office-shop',
      '/images/projects/content-office-shop/05-content-office-shop',
      '/images/projects/content-office-shop/06-content-office-shop',
      '/images/projects/content-office-shop/07-content-office-shop',
      '/images/projects/content-office-shop/10-content-office-shop',
    ],
    description: '社区公共空间室内设计，以"城市客厅"为概念，打造居民共享的多功能空间。设计强调灵活可变性和社区参与感。',
  },
  {
    id: 'content-show',
    name: 'Content Show',
    location: '上海 · 中国',
    client: '上海市绿化局',
    year: '2021',
    grossFloorArea: '65,000 m²',
    status: 'finalized',
    statusLabel: '已建成',
    category: 'show',
    categoryLabel: '秀场',
    imagePath: '/images/projects/11-content show',
    // 5个秀场视频（2009-2016），按年份从新到旧排列
    videos: [
      {
        mp4Url: 'https://video.raxlarchitects.com/2016_content_pepsi.mp4',
        title: 'Content Show 2016',
        thumbnail: '/images/projects/content-show/showVideoCover05',
      },
      {
        mp4Url: 'https://video.raxlarchitects.com/2014_content_264.mp4',
        title: 'Content Show 2014',
        thumbnail: '/images/projects/content-show/showVideoCover04',
      },
      {
        mp4Url: 'https://video.raxlarchitects.com/2013_Transparent_Hallucinogen.mp4',
        title: 'Content Show 2013',
        thumbnail: '/images/projects/content-show/showVideoCover03',
      },
      {
        mp4Url: 'https://video.raxlarchitects.com/2011_CONTENT_WHATCHING_WHATCHED.mp4',
        title: 'Content Show 2011',
        thumbnail: '/images/projects/content-show/showVideoCover02',
      },
      {
        mp4Url: 'https://video.raxlarchitects.com/2009_content_body_on_body.mp4',
        title: 'Body on Body 2009',
        thumbnail: '/images/projects/content-show/showVideoCover01',
      },
    ],
    gallery: [
      '/images/projects/content-show/01-content-show',
      '/images/projects/content-show/02-content-show',
      '/images/projects/content-show/03-content-show',
      '/images/projects/content-show/04-content-show',
      '/images/projects/content-show/05-content-show',
      '/images/projects/content-show/06-content-show',
    ],
    description: '黄浦江沿岸生态廊道规划项目，以生态修复和公众可达性为核心目标。设计构建连续的步行系统和多层次生境系统，提升城市滨水空间品质。',
  },
  // Show 项目 - 秀场视频（2009-2016）
];
