// 项目数据
// 用于首页轮播和项目页面瀑布流展示

export const projects = [
  {
    id: 'one-park-gubei',
    name: '壹方城古北',
    location: '上海',
    client: '万科集团',
    year: '2023',
    grossFloorArea: '120,000 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/one-park-gubei/01.jpg',
      '/images/projects/one-park-gubei/02.jpg',
      '/images/projects/one-park-gubei/03.jpg',
      '/images/projects/one-park-gubei/04.jpg',
    ],
    description: '古北地区的城市更新项目，融合传统与现代，打造宜居社区。设计理念源于对上海里弄文化的现代诠释，通过创新的空间组织方式，实现高密度环境下的居住品质提升。',
  },
  {
    id: 'royal-pavilion-huashan',
    name: '湖山半岛度假酒店',
    location: '苏州',
    client: '华润置地',
    year: '2022',
    grossFloorArea: '45,000 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/royal-pavilion-huashan/01.jpg',
      '/images/projects/royal-pavilion-huashan/02.jpg',
      '/images/projects/royal-pavilion-huashan/03.jpg',
      '/images/projects/royal-pavilion-huashan/04.jpg',
      '/images/projects/royal-pavilion-huashan/05.jpg',
      '/images/projects/royal-pavilion-huashan/06.jpg',
    ],
    description: '位于太湖之滨的精品度假酒店，以江南园林为设计灵感，打造私密宁静的度假体验。建筑设计强调与自然环境的和谐共生，采用大量本土材料和可持续设计策略。',
  },
  {
    id: 'gubei-art-center',
    name: '古北艺术中心',
    location: '上海',
    client: '上海建工集团',
    year: '2021',
    grossFloorArea: '8,500 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/gubei-art-center/01.jpg',
      '/images/projects/gubei-art-center/02.jpg',
      '/images/projects/gubei-art-center/03.jpg',
    ],
    description: '多功能艺术文化空间，包含展览、演出、创作等功能。设计通过灵活的空间划分和创新的流线组织，满足不同类型艺术活动的需求。',
  },
  {
    id: 'huashan-peninsula-landscape',
    name: '湖山半岛景观设计',
    location: '苏州',
    client: '华润置地',
    year: '2022',
    grossFloorArea: '85,000 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'landscape',
    categoryLabel: '景观',
    gallery: [
      '/images/projects/huashan-peninsula-landscape/01.jpg',
      '/images/projects/huashan-peninsula-landscape/02.jpg',
      '/images/projects/huashan-peninsula-landscape/03.jpg',
      '/images/projects/huashan-peninsula-landscape/04.jpg',
    ],
    description: '半岛度假区整体景观规划，以"山水相依"为设计主题，创造层次丰富的公共空间体系。设计融合本土植被与水系统，构建生态可持续的景观基础设施。',
  },
  {
    id: 'gubei-interior-renovation',
    name: '古北社区中心室内改造',
    location: '上海',
    client: '上海徐汇区政府',
    year: '2023',
    grossFloorArea: '1,200 m²',
    status: 'under-construction',
    statusLabel: '建设中',
    category: 'interior',
    categoryLabel: '室内',
    gallery: [
      '/images/projects/gubei-interior-renovation/01.jpg',
      '/images/projects/gubei-interior-renovation/02.jpg',
    ],
    description: '老旧社区公共空间室内改造升级项目，通过创新的材料和空间组织方式，改善社区使用体验。设计强调无障碍设计和多代际共享理念。',
  },
  {
    id: 'yunhu-tech-park',
    name: '云湖科技园',
    location: '杭州',
    client: '融创中国',
    year: '2020',
    grossFloorArea: '180,000 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/yunhu-tech-park/01.jpg',
      '/images/projects/yunhu-tech-park/02.jpg',
      '/images/projects/yunhu-tech-park/03.jpg',
      '/images/projects/yunhu-tech-park/04.jpg',
    ],
    description: '创新型科技园区，以"产城融合"为设计理念，打造工作、生活、学习一体化的创新生态系统。建筑群体采用模块化设计策略，适应未来发展需求。',
  },
  {
    id: 'ancient-town-renovation',
    name: '古北古镇更新',
    location: '上海',
    client: '上海徐汇区政府',
    year: '2019',
    grossFloorArea: '35,000 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/ancient-town-renovation/01.jpg',
      '/images/projects/ancient-town-renovation/02.jpg',
      '/images/projects/ancient-town-renovation/03.jpg',
    ],
    description: '历史街区保护性更新项目，在保护历史建筑肌理的同时，引入现代城市功能。设计采用"针灸式"微更新策略，最小干预、最大效益。',
  },
  {
    id: 'riverside-green-corridor',
    name: '滨江绿色廊道',
    location: '上海',
    client: '上海市绿化局',
    year: '2021',
    grossFloorArea: '65,000 m²',
    status: 'proposed',
    statusLabel: '提案中',
    category: 'landscape',
    categoryLabel: '景观',
    gallery: [
      '/images/projects/riverside-green-corridor/01.jpg',
      '/images/projects/riverside-green-corridor/02.jpg',
    ],
    description: '黄浦江沿岸生态廊道规划项目，以生态修复和公众可达性为核心目标。设计构建连续的步行系统和多层次生境系统，提升城市滨水空间品质。',
  },
  {
    id: 'urban-living-room',
    name: '城市客厅',
    location: '上海',
    client: '万科集团',
    year: '2020',
    grossFloorArea: '2,800 m²',
    status: 'finalized',
    statusLabel: '已完成',
    category: 'interior',
    categoryLabel: '室内',
    gallery: [
      '/images/projects/urban-living-room/01.jpg',
      '/images/projects/urban-living-room/02.jpg',
      '/images/projects/urban-living-room/03.jpg',
    ],
    description: '社区公共空间室内设计，以"城市客厅"为概念，打造居民共享的多功能空间。设计强调灵活可变性和社区参与感。',
  },
  {
    id: 'eco-office-tower',
    name: '生态办公楼',
    location: '上海',
    client: '保利发展',
    year: '2024',
    grossFloorArea: '28,000 m²',
    status: 'under-construction',
    statusLabel: '建设中',
    category: 'architecture',
    categoryLabel: '建筑',
    gallery: [
      '/images/projects/eco-office-tower/01.jpg',
      '/images/projects/eco-office-tower/02.jpg',
    ],
    description: '新一代生态办公建筑，以零碳运营为设计目标。建筑整合被动式设计策略、可再生能源系统和智能建筑管理系统，树立可持续办公建筑新标准。',
  },
];
